name: tester
on:
  pull_request:
    branches: [ dev ]
jobs: 
  test-validator:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout to working directory
      - uses: actions/checkout@v5
      - name: Run tests
      - run: test_lambda_function1.py
